### ISSUE TITLE
Remove google analytics tag

### ISSUE THREAD

**Issue by vjeux** [nrgapple/excalidraw-standalone#1]
Otherwise it still sends analytics to google. None of the analytics is actually user generated content but you probably don’t want it if your goal is to be 100% offline.

![FE505FD3-BF41-4E31-B916-C3448447ADF6](https://user-images.githubusercontent.com/197597/74888939-5b192200-5334-11ea-9f9e-916f6bd2c82a.png)

**Comment by nrgapple** [comment]
nice catch!

**Comment by nrgapple** [comment]
I believe I already removed this: https://github.com/nrgapple/excalidraw/commit/414afa69471686efb2612c07ddb88cefded6237b#diff-528c3923d718a8860f5d8c05c3931c55L77

Looks like I didn't transfer it though
